minimumReleaseAge: 10080
minimumReleaseAgeExclude:
    - '@eamodio/*'
    - '@gitkraken/*'
    - '@octokit/*'
    - '@types/react'
    - '@types/react-dom'
    - '@vscode/*'
    - 'react'
    - 'react-dom'
    - 'react-compiler-webpack'
