blockExoticSubdeps: true

ignoredBuiltDependencies:
    - '@parcel/watcher'
    - '@playwright/browser-chromium'
    - '@swc/core'
    - '@vscode/vsce-sign'
    - es5-ext
    - esbuild
    - keytar
    - protobufjs
    - rs-module-lexer
    - sharp
    - ttf2woff2
    - unrs-resolver

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
    - '@eamodio/*'
    - '@gitkraken/*'
    - '@vscode/*'
    - '@typescript-eslint/*'
    - 'typescript-eslint'
    - '@e18e/eslint-plugin@0.2.0'
    - 'webpack@5.105.2'

patchedDependencies:
    fantasticon@4.1.0: patches/fantasticon@4.1.0.patch
