packages:
    - '.'
    - 'packages/*'
    - 'packages/plus/*'

allowBuilds:
    '@parcel/watcher': false
    '@playwright/browser-chromium': false
    '@swc/core': false
    '@vscode/vsce-sign': false
    es5-ext: false
    esbuild: false
    keytar: false
    rs-module-lexer: false
    sharp: false
    ttf2woff2: false
    unrs-resolver: false

blockExoticSubdeps: true

catalog:
    '@types/mocha': 10.0.10
    '@types/sinon': 21.0.1
    mocha: 11.7.6
    sinon: 22.0.0
    tinybench: 6.0.2
    tsx: 4.22.3
    typescript: 6.0.3

enableGlobalVirtualStore: true

minimumReleaseAge: 7200

minimumReleaseAgeExclude:
    - '@eamodio/*'
    - '@gitkraken/*'
    - '@vscode/*'

packageExtensions:
    '@gitkraken/gitkraken-components':
        dependencies:
            '@types/react': '*'
            '@types/react-dom': '*'

patchedDependencies:
    fantasticon@4.1.0: patches/fantasticon@4.1.0.patch
