minimumReleaseAge: 10080
minimumReleaseAgeExclude:
    - '@eamodio/*'
    - '@gitkraken/*'
    - '@vscode/*'
    - '@eslint/compat@2.0.0'
    - '@eslint/core@1.0.0'
    - '@octokit/request*'
    - '@prettier/plugin-oxc@0.0.5'
    - '@swc/core@1.15.1'
    - '@types/react@19.2.5'
    - '@types/react-dom@19.2.3'
    - 'esbuild-node-externals@1.20.1'
    - 'glob@13.0.0'
    - 'ovsx@0.10.7'
    - 'react-compiler-webpack@1.0.0'
    - 'webpack@5.103.0'
    - 'webpack-bundle-analyzer@5.0.1'
