/*global document window*/
import type GraphContainer from '@gitkraken/gitkraken-components';
import type {
	CssVariables,
	GraphRow,
	GraphZoneType,
	ReadonlyGraphRow,
	SelectCommitsOptions,
	WorkDirStats,
} from '@gitkraken/gitkraken-components';
import { consume } from '@lit/context';
import { SignalWatcher } from '@lit-labs/signals';
import { html, LitElement } from 'lit';
import { customElement, query, state } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import type { GitGraphRowType } from '@gitlens/git/models/graph.js';
import type { GitCommitReachability } from '@gitlens/git/providers/commits.js';
import { filterMap } from '@gitlens/utils/array.js';
import { getCssMixedColorValue, getCssOpacityColorValue, getCssVariable } from '@gitlens/utils/color.js';
import { debounce } from '@gitlens/utils/debounce.js';
import { areEqual } from '@gitlens/utils/object.js';
import type { CommitDetails } from '../../../../commitDetails/protocol.js';
import type {
	GraphAvatars,
	GraphScope,
	GraphSelection,
	GraphWipMetadataBySha,
	RowAction,
} from '../../../../plus/graph/protocol.js';
import {
	DoubleClickedCommand,
	EnsureRowRequest,
	GetMissingAvatarsCommand,
	GetMissingRefsMetadataCommand,
	GetMoreRowsCommand,
	GetWipStatsRequest,
	RowActionCommand,
	SyncWipWatchesCommand,
	UpdateColumnsCommand,
	UpdateRefsVisibilityCommand,
	UpdateSelectionCommand,
} from '../../../../plus/graph/protocol.js';
import type { CustomEventType } from '../../../shared/components/element.js';
import { ipcContext } from '../../../shared/contexts/ipc.js';
import type { TelemetryContext } from '../../../shared/contexts/telemetry.js';
import { telemetryContext } from '../../../shared/contexts/telemetry.js';
import type { Disposable } from '../../../shared/events.js';
import type { ThemeChangeEvent } from '../../../shared/theme.js';
import { onDidChangeTheme } from '../../../shared/theme.js';
import { graphStateContext } from '../context.js';
import { filterSecondariesForScope } from '../utils/wip.utils.js';
import type { GlGraph } from './gl-graph.js';
import type { GraphWrapperTheming } from './gl-graph.react.jsx';
import './gl-graph.js';

// Builds the display message for a WIP row. Uses "Working Changes" when stats show any activity,
// "Working Tree" when stats are known-empty or not yet fetched. The label (worktree name) is
// appended in parens for secondary WIP rows.
function wipRowMessage(label: string | undefined, stats: WorkDirStats | undefined): string {
	const hasChanges =
		stats != null && ((stats.added ?? 0) > 0 || (stats.modified ?? 0) > 0 || (stats.deleted ?? 0) > 0);
	const base = hasChanges ? 'Working Changes' : 'Working Tree';
	return label != null ? `${base} (${label})` : base;
}

// Builds a "lite" CommitDetails from a graph row so the details panel can paint the commit
// shell synchronously on selection — no IPC roundtrip required for the metadata bar/header.
// `files`/`stats` stay undefined and get filled in by the subsequent full fetch.
// committer is duplicated from author (graph row only carries one identity); the full fetch
// reconciles it. avatar is resolved synchronously from the host-supplied email→URL map so the
// embedded gl-commit-author doesn't flash its `person` fallback icon between selections; if the
// email isn't yet in the map, the full fetch will supply the URL.
function buildCommitLite(
	row: { sha: string; parents: string[]; author: string; email: string; date: number; message: string },
	repoPath: string,
	avatars: GraphAvatars | undefined,
): CommitDetails {
	const date = new Date(row.date);
	const avatar = row.email ? avatars?.[row.email] : undefined;
	return {
		sha: row.sha,
		shortSha: row.sha.slice(0, 7),
		message: row.message,
		author: { name: row.author, email: row.email, date: date, avatar: avatar },
		committer: { name: row.author, email: row.email, date: date, avatar: avatar },
		parents: row.parents,
		repoPath: repoPath,
	};
}

// These properties in the DOM are auto-generated by VS Code from our `contributes.colors` in package.json
const graphLaneThemeColors = new Map([
	['--vscode-gitlens-graphLane1Color', '#15a0bf'],
	['--vscode-gitlens-graphLane2Color', '#0669f7'],
	['--vscode-gitlens-graphLane3Color', '#8e00c2'],
	['--vscode-gitlens-graphLane4Color', '#c517b6'],
	['--vscode-gitlens-graphLane5Color', '#d90171'],
	['--vscode-gitlens-graphLane6Color', '#cd0101'],
	['--vscode-gitlens-graphLane7Color', '#f25d2e'],
	['--vscode-gitlens-graphLane8Color', '#f2ca33'],
	['--vscode-gitlens-graphLane9Color', '#7bd938'],
	['--vscode-gitlens-graphLane10Color', '#2ece9d'],
]);

declare global {
	// interface HTMLElementTagNameMap {
	// 	'gl-graph-wrapper': GlGraphWrapper;
	// }

	interface GlobalEventHandlersEventMap {
		// passing up event map
		'gl-graph-change-selection': CustomEvent<{
			selection: GraphSelection[];
			reachability?: GitCommitReachability;
			/** Per-sha commit shell (no files/stats) for synchronous first paint of the details panel. */
			commits?: Record<string, CommitDetails>;
		}>;
		'gl-graph-change-visible-days': CustomEvent<{ top: number; bottom: number }>;
		'gl-graph-mouse-leave': CustomEvent<void>;
		'gl-graph-row-context-menu': CustomEvent<{ graphZoneType: GraphZoneType; graphRow: GraphRow }>;
		'gl-graph-row-double-click': CustomEvent<{ graphRow: GraphRow; preserveFocus?: boolean }>;
		'gl-graph-row-hover': CustomEvent<{
			graphZoneType: GraphZoneType;
			graphRow: GraphRow;
			clientX: number;
			currentTarget: HTMLElement;
		}>;
		'gl-graph-row-unhover': CustomEvent<{
			graphZoneType: GraphZoneType;
			graphRow: GraphRow;
			relatedTarget: EventTarget | null;
		}>;
	}
}

@customElement('gl-graph-wrapper')
export class GlGraphWrapper extends SignalWatcher(LitElement) {
	// use Light DOM
	protected override createRenderRoot(): HTMLElement | DocumentFragment {
		return this;
	}

	private disposables: Disposable[] = [];

	@consume({ context: graphStateContext, subscribe: true })
	private readonly graphState!: typeof graphStateContext.__context__;

	@consume({ context: ipcContext })
	private readonly _ipc!: typeof ipcContext.__context__;

	@consume({ context: telemetryContext as any })
	private readonly _telemetry!: TelemetryContext;

	@query('gl-graph')
	graph!: typeof GlGraph;

	private ref?: GraphContainer;
	private onSetRef = (ref: GraphContainer) => {
		this.ref = ref;
	};

	scrollGraphBy(deltaY: number): void {
		if (this.ref == null) return;
		this.ref.setScrollTop((this.ref.scrollTop ?? 0) + deltaY);
	}

	@state()
	private theming?: GraphWrapperTheming;

	override connectedCallback(): void {
		super.connectedCallback?.();

		this.theming = this.getGraphTheming();
		this.disposables.push(
			onDidChangeTheme(
				debounce((e: ThemeChangeEvent) => {
					this.theming = this.getGraphTheming(e);
				}, 100),
			),
		);

		document.addEventListener('gl-jump-to-pinned-branch', this.onJumpToPinnedBranch as EventListener);
	}

	override disconnectedCallback(): void {
		super.disconnectedCallback?.();

		document.removeEventListener('gl-jump-to-pinned-branch', this.onJumpToPinnedBranch as EventListener);
		this.disposables.forEach(d => d.dispose());
		this.disposables = [];
	}

	private onJumpToPinnedBranch = (e: CustomEvent<{ sha: string }>) => {
		this.ensureAndSelectCommit(e.detail.sha);
	};

	// Cache keyed by the quad (rows, wipMetadataBySha, workingTreeStats, scope) — any reference
	// change invalidates. Scope must be in the key because the secondary-WIP scope filter below
	// (`filterSecondariesForScope`) reads `scope.branchRef`/`upstreamRef`/`additionalBranchRefs`,
	// so the cached result is stale when scope changes even if the row/metadata refs don't.
	private _decoratedRowsCache?: {
		rows: GraphRow[] | undefined;
		wipMetadataBySha: GraphWipMetadataBySha | undefined;
		workingTreeStats: typeof graphStateContext.__context__.workingTreeStats;
		scope: GraphScope | undefined;
		result: GraphRow[] | undefined;
	};

	// Injects a synthetic primary WIP row at [0] and per-worktree secondary WIP rows
	// immediately after, so the GK component renders one row per worktree. The component's
	// own auto-inject is skipped because rows[0] already has type `work-dir-changes`.
	private getDecoratedRows(): GraphRow[] | undefined {
		const { graphState } = this;
		const rows = graphState.rows;
		const wipMetadataBySha = graphState.wipMetadataBySha;
		const workingTreeStats = graphState.workingTreeStats;
		const scope = graphState.scope;

		const cached = this._decoratedRowsCache;
		if (
			cached != null &&
			cached.rows === rows &&
			cached.wipMetadataBySha === wipMetadataBySha &&
			cached.workingTreeStats === workingTreeStats &&
			cached.scope === scope
		) {
			return cached.result;
		}

		const filteredMetadata = filterSecondariesForScope(wipMetadataBySha, scope);

		let result: GraphRow[] | undefined;
		if (rows == null || filteredMetadata == null || Object.keys(filteredMetadata).length === 0) {
			// Let the GK component handle the primary WIP auto-inject from workingTreeStats.
			result = rows?.slice();
		} else {
			// The GK component mutates the passed array via unshift on each render, so rows[0] may
			// already be a primary work-dir row from a previous pass. Strip it to avoid duplicates —
			// we inject our own primary below with the same role.
			const realRows = rows[0]?.type === 'work-dir-changes' ? rows.slice(1) : rows;
			const headRefSha = realRows.find(r => r.heads?.some(h => h.isCurrentHead))?.sha ?? realRows[0]?.sha;

			const now = Date.now();
			const primary: GraphRow = {
				sha: 'work-dir-changes',
				parents: headRefSha ? [headRefSha] : [],
				author: '',
				email: '',
				date: now,
				message: wipRowMessage(undefined, workingTreeStats),
				type: 'work-dir-changes',
				heads: [],
				remotes: [],
				tags: [],
				...(workingTreeStats?.context ? { contexts: { row: workingTreeStats.context } } : {}),
			};

			// Group secondary WIP rows by the index of their parent commit in `realRows`, so each
			// worktree's WIP row renders directly above the commit it's anchored at. Worktrees whose
			// HEAD isn't in the loaded/visible rows (hidden branch, beyond paging limit) are dropped —
			// a floating WIP row with no anchor in the graph is more confusing than missing one.
			const realRowIndexBySha = new Map<string, number>();
			for (let i = 0; i < realRows.length; i++) {
				realRowIndexBySha.set(realRows[i].sha, i);
			}

			const secondariesByParentIdx = new Map<number, GraphRow[]>();
			for (const [sha, meta] of Object.entries(filteredMetadata)) {
				const idx = realRowIndexBySha.get(meta.parentSha);
				if (idx == null) continue;

				const row: GraphRow = {
					sha: sha,
					parents: [meta.parentSha],
					author: '',
					email: '',
					date: now,
					message: wipRowMessage(meta.label, meta.workDirStats),
					type: 'work-dir-changes',
					heads: [],
					remotes: [],
					tags: [],
				};
				const existing = secondariesByParentIdx.get(idx);
				if (existing != null) {
					existing.push(row);
				} else {
					secondariesByParentIdx.set(idx, [row]);
				}
			}

			const interleaved: GraphRow[] = [primary];
			for (let i = 0; i < realRows.length; i++) {
				const atThisIdx = secondariesByParentIdx.get(i);
				if (atThisIdx != null) {
					interleaved.push(...atThisIdx);
				}
				interleaved.push(realRows[i]);
			}

			result = interleaved;
		}

		this._decoratedRowsCache = {
			rows: rows,
			wipMetadataBySha: wipMetadataBySha,
			workingTreeStats: workingTreeStats,
			scope: scope,
			result: result,
		};
		return result;
	}

	override render() {
		const { graphState } = this;

		return html`<gl-graph
			.setRef=${this.onSetRef}
			.activeRow=${graphState.activeRow}
			.avatars=${graphState.avatars}
			.columns=${graphState.columns}
			.config=${graphState.config}
			.context=${graphState.context}
			.downstreams=${graphState.downstreams}
			.excludeRefs=${graphState.excludeRefs}
			.excludeTypes=${graphState.excludeTypes}
			.includeOnlyRefs=${graphState.includeOnlyRefs}
			.pinnedRef=${graphState.pinnedRef}
			?loading=${graphState.loading}
			nonce=${ifDefined(graphState.nonce)}
			.paging=${graphState.paging}
			.refsMetadata=${graphState.refsMetadata}
			.rows=${this.getDecoratedRows()}
			.rowsStats=${graphState.rowsStats}
			?rowsStatsLoading=${graphState.rowsStatsLoading}
			.searchMode=${graphState.searchMode}
			.searchResults=${graphState.searchResults}
			.selectedRows=${graphState.selectedRows}
			.theming=${this.theming}
			?windowFocused=${graphState.windowFocused}
			.workingTreeStats=${graphState.workingTreeStats}
			.wipMetadataBySha=${graphState.wipMetadataBySha}
			.wipShasSettleDelayMs=${GlGraphWrapper.wipShasSettleDelayMs}
			.scope=${graphState.scope}
			@changecolumns=${this.onColumnsChanged}
			@changerefsvisibility=${this.onRefsVisibilityChanged}
			@changeselection=${this.onSelectionChanged}
			@changevisibledays=${this.onVisibleDaysChanged}
			@missingavatars=${this.onMissingAvatars}
			@missingrefsmetadata=${this.onMissingRefsMetadata}
			@morerows=${this.onGetMoreRows}
			@graphmouseleave=${this.onMouseLeave}
			@refdoubleclick=${this.onRefDoubleClick}
			@rowaction=${this.onRowAction}
			@rowcontextmenu=${this.onRowContextMenu}
			@rowdoubleclick=${this.onRowDoubleClick}
			@rowhover=${this.onRowHover}
			@rowunhover=${this.onRowUnhover}
			@scopeanchorsunreachable=${this.onScopeAnchorsUnreachable}
			@wipshasmissingstats=${this.onWipShasMissingStats}
			@visiblewipshaschanged=${this.onVisibleWipShasChanged}
		></gl-graph>`;
	}

	override focus(): void {
		this.ref?.focus();
	}

	getCommits(shas: string[]): ReadonlyGraphRow[] {
		return this.ref?.getCommits(shas) ?? [];
	}

	selectCommits(shas: string[], options?: SelectCommitsOptions): ReadonlyGraphRow[] {
		return this.ref?.selectCommits(shas, options) ?? [];
	}

	/**
	 * Select a row by SHA, loading it into the graph first if necessary.
	 * The host handles both loading and selecting — the rows notification
	 * carries the updated selection so the graph renders it automatically.
	 */
	ensureAndSelectCommit(sha: string): void {
		// Fast path — row already loaded
		if (this.ref?.getCommits([sha])?.length) {
			this.ref.selectCommits([sha], { ensureVisible: true });
			return;
		}

		// Ask the host to load and select the row; the rows notification
		// will carry the selection so the graph picks it up on render.
		this.graphState.loading = true;
		void this._ipc.sendRequest(EnsureRowRequest, { id: sha, select: true });
	}

	private onColumnsChanged(event: CustomEventType<'graph-changecolumns'>) {
		this._ipc.sendCommand(UpdateColumnsCommand, { config: event.detail.settings });
	}

	private onGetMoreRows({ detail: sha }: CustomEventType<'graph-morerows'>) {
		this.graphState.loading = true;
		this._ipc.sendCommand(GetMoreRowsCommand, { id: sha });
	}

	private onMouseLeave() {
		this.dispatchEvent(new CustomEvent('gl-graph-mouse-leave'));
	}

	private onMissingAvatars({ detail: emails }: CustomEventType<'graph-missingavatars'>) {
		this._ipc.sendCommand(GetMissingAvatarsCommand, { emails: emails });
	}

	private onMissingRefsMetadata({ detail: metadata }: CustomEventType<'graph-missingrefsmetadata'>) {
		this._ipc.sendCommand(GetMissingRefsMetadataCommand, { metadata: metadata });
	}

	private onRefDoubleClick({ detail: { ref, metadata } }: CustomEventType<'graph-doubleclickref'>) {
		this._ipc.sendCommand(DoubleClickedCommand, { type: 'ref', ref: ref, metadata: metadata });
	}

	private onRefsVisibilityChanged({ detail }: CustomEventType<'graph-changerefsvisibility'>) {
		this._ipc.sendCommand(UpdateRefsVisibilityCommand, detail);
	}

	private onRowAction({ detail: { action, row } }: CustomEvent<{ action: RowAction; row: GraphRow }>) {
		this._ipc.sendCommand(RowActionCommand, { action: action, row: { id: row.sha, type: row.type } });
	}

	private onRowContextMenu({ detail: { graphRow, graphZoneType } }: CustomEventType<'graph-rowcontextmenu'>) {
		this.dispatchEvent(
			new CustomEvent('gl-graph-row-context-menu', {
				detail: { graphZoneType: graphZoneType, graphRow: graphRow },
			}),
		);
	}

	private onRowDoubleClick({ detail: { row, preserveFocus } }: CustomEventType<'graph-doubleclickrow'>) {
		this.dispatchEvent(
			new CustomEvent('gl-graph-row-double-click', {
				detail: { graphRow: row, preserveFocus: preserveFocus },
			}),
		);
		this._ipc.sendCommand(DoubleClickedCommand, {
			type: 'row',
			row: { id: row.sha, type: row.type },
			preserveFocus: preserveFocus,
		});
	}

	private onRowHover({ detail }: CustomEventType<'graph-graphrowhovered'>) {
		this.dispatchEvent(new CustomEvent('gl-graph-row-hover', { detail: detail }));
	}

	private onRowUnhover({ detail }: CustomEventType<'graph-graphrowunhovered'>) {
		this.dispatchEvent(new CustomEvent('gl-graph-row-unhover', { detail: detail }));
	}

	private _lastSentSelectionKey: string | undefined;
	private onSelectionChanged({ detail: { rows, focusedRow } }: CustomEventType<'graph-changeselection'>) {
		const wipMetadataBySha = this.graphState.wipMetadataBySha;
		const selection: GraphSelection[] = filterMap(rows, r =>
			r != null
				? ({
						id: r.sha,
						type: r.type,
						active: r === focusedRow,
						hidden: r.hidden,
						repoPath: wipMetadataBySha?.[r.sha]?.repoPath,
					} satisfies GraphSelection)
				: undefined,
		);

		const activeKey = focusedRow != null ? `${focusedRow.sha}|${focusedRow.date}` : undefined;
		this.graphState.activeRow = activeKey;
		this.graphState.activeDay = focusedRow?.date;

		// Build per-sha commit shells from the underlying row data so the details panel can
		// paint the commit metadata synchronously (no IPC roundtrip) on cold-cache selections.
		// Skip WIP / work-dir-changes rows — they don't map to a commit shell.
		const sourceRows = this.graphState.rows;
		const repositories = this.graphState.repositories;
		const selectedRepoId = this.graphState.selectedRepository;
		const fallbackRepoPath =
			(selectedRepoId != null ? repositories?.find(r => r.id === selectedRepoId)?.path : undefined) ??
			repositories?.[0]?.path;
		const sourceRowBySha = sourceRows != null ? new Map(sourceRows.map(r => [r.sha, r])) : undefined;
		let commits: Record<string, CommitDetails> | undefined;
		if (sourceRowBySha != null) {
			for (const sel of selection) {
				if (sel.type === ('work-dir-changes' satisfies GitGraphRowType)) continue;
				const sourceRow = sourceRowBySha.get(sel.id);
				if (sourceRow == null) continue;
				const repoPath = sel.repoPath ?? fallbackRepoPath;
				if (repoPath == null) continue;
				commits ??= {};
				commits[sel.id] = buildCommitLite(sourceRow, repoPath, this.graphState.avatars);
			}
		}

		// Look up reachability from our original row data (the GK components
		// processed row doesn't preserve custom properties from GitGraphRow)
		const reachability =
			focusedRow != null
				? (sourceRowBySha?.get(focusedRow.sha) as { reachability?: GitCommitReachability } | undefined)
						?.reachability
				: undefined;

		this.dispatchEvent(
			new CustomEvent('gl-graph-change-selection', {
				detail: { selection: selection, reachability: reachability, commits: commits },
			}),
		);

		// Dedup host RPC: the GK component fires `graph-changeselection` on focus-row changes too, which
		// can trip during scroll without any real selection change. Skip the IPC when the selection set
		// (including active/hidden flags) matches what we last sent.
		const selectionKey = selection
			.map(s => `${s.id}|${s.type}|${s.repoPath ?? ''}|${s.active ? 1 : 0}|${s.hidden ? 1 : 0}`)
			.join(',');
		if (selectionKey === this._lastSentSelectionKey) return;
		this._lastSentSelectionKey = selectionKey;

		this._ipc.sendCommand(UpdateSelectionCommand, { selection: selection });
	}

	private onVisibleDaysChanged({ detail }: CustomEventType<'graph-changevisibledays'>) {
		this.dispatchEvent(new CustomEvent('gl-graph-change-visible-days', { detail: detail }));
	}

	/**
	 * SHAs we've already issued `GetMoreRowsCommand({ id: sha })` for via the unreachable-anchor
	 * path, mapped to the loaded row count at the time the request was sent. If a targeted walk
	 * returns without surfacing the SHA, we park it here so the next `scopeanchorsunreachable`
	 * event doesn't re-fire the same request immediately. Entries are released two ways:
	 * (a) scope reference changes (user re-scopes, or refs-moved invalidation produces a new
	 *     scope object), which clears the entire map;
	 * (b) the host response delivered new rows, growing `rows.length` past the snapshot — the
	 *     provider's cursor advanced past where the previous walk's `limit * 10` cap aborted,
	 *     so a retry continues the walk from the new cursor rather than re-running the same
	 *     range. Entries whose request didn't grow rows stay parked: retrying would hit the
	 *     same cap at the same cursor with no progress.
	 */
	private _unreachableAnchorRequests = new Map<string, number>();
	private _unreachableAnchorScope: typeof graphStateContext.__context__.scope = undefined;

	private onScopeAnchorsUnreachable(event: CustomEvent<Set<string>>) {
		// The component flagged that one or more scope anchors can't reach a visible ancestor
		// within the loaded graph rows (merge base not yet fetched). Ask the host for more rows
		// so the synthetic edges can resolve.
		if (this.graphState.loading || !this.graphState.paging?.hasMore) return;

		// Drop prior dedupe state when the live scope reference changes — the stateProvider
		// assigns a new scope object on every transition (re-scope, post-invalidation re-resolve),
		// so reference inequality cleanly catches both.
		const scope = this.graphState.scope;
		if (scope !== this._unreachableAnchorScope) {
			this._unreachableAnchorRequests.clear();
			this._unreachableAnchorScope = scope;
		}

		// Forward an unreachable anchor SHA to the host so the provider's page-until-found path
		// (graph.ts getCommitsForGraphCore stop logic) loads enough rows in one round trip,
		// instead of one page per scope toggle. Also short-circuit if the flagged anchors are
		// already in the loaded rows — guards against stale unreachable events fired during
		// scope-swap re-renders.
		const anchors = event.detail;
		const rows = this.graphState.rows;
		if (anchors?.size && rows?.length) {
			const loaded = new Set(rows.map(r => r.sha));
			const rowCount = rows.length;

			// Release any prior request whose response delivered new rows — the provider's cursor
			// advanced past where the previous walk's cap aborted, so retrying continues the walk
			// from the new cursor instead of re-running the same range.
			for (const [sha, requestedAtCount] of this._unreachableAnchorRequests) {
				if (rowCount > requestedAtCount) {
					this._unreachableAnchorRequests.delete(sha);
				}
			}

			const missing = [...anchors].find(sha => !loaded.has(sha) && !this._unreachableAnchorRequests.has(sha));
			if (missing == null) return;

			this._unreachableAnchorRequests.set(missing, rowCount);
			this.graphState.loading = true;
			this._ipc.sendCommand(GetMoreRowsCommand, { id: missing });
			return;
		}

		this.graphState.loading = true;
		this._ipc.sendCommand(GetMoreRowsCommand, { id: undefined });
	}

	private _lastSyncedWipShas: Set<string> | undefined;

	/**
	 * How long a secondary WIP row must settle in the viewport before the GK component fires
	 * `onWipShasMissingStats` for it. Library default is 100ms; we raise it so rows that only flash
	 * through during fast scrolls never trigger stats work. Re-entry works because the library prunes
	 * its `requestedMissingWipStats` dedup for shas that leave the viewport.
	 */
	private static readonly wipShasSettleDelayMs = 350;

	private onVisibleWipShasChanged(event: CustomEvent<Record<string, true>>) {
		// The GK component tells us the full current set of secondary WIP rows in the viewport.
		// The host diffs against its own subscription map and opens/closes FS watchers as needed.
		const shas = Object.keys(event.detail);

		// Defensive dedup against repeat-identical sets (the library's settle-delay collapses most dupes,
		// but a round-trip through viewport edges can still emit the same set back to back).
		if (this._lastSyncedWipShas?.size === shas.length && shas.every(s => this._lastSyncedWipShas!.has(s))) {
			return;
		}
		this._lastSyncedWipShas = new Set(shas);
		this._ipc.sendCommand(SyncWipWatchesCommand, { shas: shas });
	}

	private async onWipShasMissingStats(event: CustomEvent<Record<string, true>>) {
		const shas = Object.keys(event.detail);
		if (shas.length === 0) return;

		const response = await this._ipc.sendRequest(GetWipStatsRequest, { shas: shas });
		if (response == null) return;

		// Merge fetched stats into `wipMetadataBySha`. Skipping no-op entries via `wipStatsEqual` preserves
		// the prior reference so downstream reactive consumers don't churn.
		const existing = this.graphState.wipMetadataBySha;
		if (existing == null) return;

		let next: GraphWipMetadataBySha | undefined;
		for (const sha of shas) {
			const prev = existing[sha];
			if (prev == null) continue;

			const incomingStats = response[sha];
			if (!prev.workDirStatsStale && areEqual(prev.workDirStats, incomingStats)) continue;

			next ??= { ...existing };
			next[sha] = { ...prev, workDirStats: incomingStats, workDirStatsStale: false };
		}
		if (next == null) return;

		this.graphState.wipMetadataBySha = next;
	}

	private readonly themingDefaults: { cssVariables: CssVariables; themeOpacityFactor: number } = {
		cssVariables: (() => {
			const bgColor = getCssVariableValue('--color-background');
			const mixedGraphColors: CssVariables = {};
			let i = 0;
			let color;
			for (const [colorVar, colorDefault] of graphLaneThemeColors) {
				color = getCssVariableValue(colorVar, { fallbackValue: colorDefault });
				mixedGraphColors[`--graph-color-${i}`] = color;
				for (const mixInt of [15, 25, 45, 50]) {
					mixedGraphColors[`--graph-color-${i}-bg${mixInt}`] = getCssMixedColorValue(bgColor, color, mixInt);
				}
				for (const mixInt of [10, 50]) {
					mixedGraphColors[`--graph-color-${i}-f${mixInt}`] = getCssOpacityColorValue(color, mixInt);
				}
				i++;
			}
			return {
				'--app__bg0': getCssVariableValue('--color-graph-background'),
				'--panel__bg0': getCssVariableValue('--color-graph-background1'),
				'--panel__bg1': getCssVariableValue('--color-graph-background2'),
				'--section-border': getCssVariableValue('--color-graph-background2'),
				'--selected-row': getCssVariableValue('--color-graph-selected-row'),
				'--selected-row-border': 'none',
				'--hover-row': getCssVariableValue('--color-graph-hover-row'),
				'--hover-row-border': 'none',
				'--scrollable-scrollbar-thickness': getCssVariableValue('--graph-column-scrollbar-thickness'),
				'--scroll-thumb-bg': getCssVariableValue('--vscode-scrollbarSlider-background'),
				'--scroll-marker-head-color': getCssVariableValue('--color-graph-scroll-marker-head'),
				'--scroll-marker-upstream-color': getCssVariableValue('--color-graph-scroll-marker-upstream'),
				'--scroll-marker-highlights-color': getCssVariableValue('--color-graph-scroll-marker-highlights'),
				'--scroll-marker-local-branches-color': getCssVariableValue(
					'--color-graph-scroll-marker-local-branches',
				),
				'--scroll-marker-remote-branches-color': getCssVariableValue(
					'--color-graph-scroll-marker-remote-branches',
				),
				'--scroll-marker-stashes-color': getCssVariableValue('--color-graph-scroll-marker-stashes'),
				'--scroll-marker-tags-color': getCssVariableValue('--color-graph-scroll-marker-tags'),
				'--scroll-marker-selection-color': getCssVariableValue('--color-graph-scroll-marker-selection'),
				'--scroll-marker-pull-requests-color': getCssVariableValue('--color-graph-scroll-marker-pull-requests'),
				'--scroll-marker-wip-color': getCssVariableValue('--color-graph-scroll-marker-wip'),
				'--stats-added-color': getCssVariableValue('--color-graph-stats-added'),
				'--stats-deleted-color': getCssVariableValue('--color-graph-stats-deleted'),
				'--stats-files-color': getCssVariableValue('--color-graph-stats-files'),
				'--stats-bar-border-radius': getCssVariableValue('--graph-stats-bar-border-radius'),
				'--stats-bar-height': getCssVariableValue('--graph-stats-bar-height'),
				'--text-selected': getCssVariableValue('--color-graph-text-selected'),
				'--text-selected-row': getCssVariableValue('--color-graph-text-selected-row'),
				'--text-hovered': getCssVariableValue('--color-graph-text-hovered'),
				'--text-dimmed-selected': getCssVariableValue('--color-graph-text-dimmed-selected'),
				'--text-dimmed': getCssVariableValue('--color-graph-text-dimmed'),
				'--text-normal': getCssVariableValue('--color-graph-text-normal'),
				'--text-secondary': getCssVariableValue('--color-graph-text-secondary'),
				'--text-disabled': getCssVariableValue('--color-graph-text-disabled'),
				'--text-accent': getCssVariableValue('--color-link-foreground'),
				'--text-inverse': getCssVariableValue('--vscode-input-background'),
				'--text-bright': getCssVariableValue('--vscode-input-background'),
				...mixedGraphColors,
			};
		})(),
		themeOpacityFactor: 1,
	};

	private getGraphTheming(e?: ThemeChangeEvent): GraphWrapperTheming {
		// this will be called on theme updated as well as on config updated since it is dependent on the column colors from config changes and the background color from the theme
		const computedStyle = e?.computedStyle ?? window.getComputedStyle(document.documentElement);
		const bgColor = getCssVariableValue('--color-background', { computedStyle: computedStyle });

		const mixedGraphColors: CssVariables = {};

		let i = 0;
		let color;
		for (const [colorVar, colorDefault] of graphLaneThemeColors) {
			color = getCssVariableValue(colorVar, { computedStyle: computedStyle, fallbackValue: colorDefault });

			mixedGraphColors[`--column-${i}-color`] = getCssVariable(colorVar, computedStyle) || colorDefault;

			for (const mixInt of [15, 25, 45, 50]) {
				mixedGraphColors[`--graph-color-${i}-bg${mixInt}`] = getCssMixedColorValue(bgColor, color, mixInt);
			}

			i++;
		}

		const isHighContrastTheme =
			e?.isHighContrastTheme ??
			(document.body.classList.contains('vscode-high-contrast') ||
				document.body.classList.contains('vscode-high-contrast-light'));

		return {
			cssVariables: {
				...this.themingDefaults.cssVariables,
				'--selected-row-border': isHighContrastTheme
					? `1px solid ${getCssVariableValue('--color-graph-contrast-border', { computedStyle: computedStyle })}`
					: 'none',
				'--hover-row-border': isHighContrastTheme
					? `1px dashed ${getCssVariableValue('--color-graph-contrast-border', { computedStyle: computedStyle })}`
					: 'none',
				...mixedGraphColors,
			},
			themeOpacityFactor:
				parseInt(getCssVariable('--graph-theme-opacity-factor', computedStyle)) ||
				this.themingDefaults.themeOpacityFactor,
		};
	}
}

function getCssVariableValue(
	variable: string,
	options?: { computedStyle?: CSSStyleDeclaration; fallbackValue?: string },
): string {
	const fallbackValue = options?.computedStyle
		? getCssVariable(variable, options?.computedStyle)
		: options?.fallbackValue
			? options.fallbackValue
			: undefined;

	if (fallbackValue) {
		return `var(${variable}, ${fallbackValue})`;
	}
	return `var(${variable})`;
}
