/* oxlint-disable no-template-curly-in-string -- descriptor data contains literal GitLens format tokens */
import * as l10n from '@vscode/l10n';
import type { SettingsCategory } from '../model.js';

export const annotationsCategories: SettingsCategory[] = [
	{
		id: 'current-line',
		settingsSearch: 'gitlens.currentLine',
		name: l10n.t('Inline Blame'),
		group: 'Editor',
		icon: 'eye',
		hint: l10n.t('Adds an unobtrusive blame annotation at the end of the current line'),
		master: {
			kind: 'check',
			key: 'currentLine.enabled',
			label: l10n.t('Inline Blame'),
			addSettingsOff: [['hovers.currentLine.over', 'line']],
		},
		command: { label: l10n.t('GitLens: Toggle Line Blame Annotations'), command: 'gitlens.toggleLineBlame' },
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/gitlens-features/#current-line-blame',
		preview: 'blame',
		controls: [
			{
				kind: 'check',
				key: 'currentLine.pullRequests.enabled',
				label: l10n.t('Show the Pull Request (if any) that introduced the commit'),
				enabledWhen: 'currentLine.enabled',
			},
			{
				kind: 'info',
				text: l10n.t('Requires a connection to a supported remote service (e.g. GitHub)'),
				visibleWhen: 'currentLine.pullRequests.enabled',
			},
			{
				kind: 'text',
				key: 'currentLine.format',
				label: l10n.t('Annotation format'),
				placeholder: "${author, }${agoOrDate}${' via 'pullRequest}${ • message|50?}",
				defaultValue: "${author, }${agoOrDate}${' via 'pullRequest}${ • message|50?}",
				preview: { type: 'commit', default: "${author, }${agoOrDate}${' via 'pullRequest}${ • message|50?}" },
				tokens: true,
				enabledWhen: 'currentLine.enabled',
			},
			{
				kind: 'check',
				key: 'currentLine.useUncommittedChangesFormat',
				type: 'custom',
				label: l10n.t('Override format for uncommitted changes'),
				enabledWhen: 'currentLine.enabled',
			},
			{
				kind: 'text',
				key: 'currentLine.uncommittedChangesFormat',
				label: l10n.t('Uncommitted changes format'),
				placeholder: l10n.t('format for uncommitted changes'),
				defaultValue: '',
				preview: { type: 'commit-uncommitted', default: '' },
				tokens: true,
				enabledWhen: 'currentLine.enabled',
				visibleWhen: 'currentLine.useUncommittedChangesFormat',
				indent: true,
			},
			{
				kind: 'text',
				key: 'currentLine.dateFormat',
				label: l10n.t('Date format'),
				placeholder: l10n.t('defaults to `{setting}` value', { setting: 'defaultDateFormat' }),
				hint: l10n.t('Used for absolute dates (e.g. the {token} token) in the annotation format above', {
					token: '${date}',
				}),
				preview: { type: 'date', default: 'MMMM Do, YYYY h:mma', defaultLookup: 'defaultDateFormat' },
				enabledWhen: 'currentLine.enabled',
			},
			{
				kind: 'check',
				key: 'currentLine.scrollable',
				label: l10n.t('Include the annotation when scrolling the editor horizontally'),
				hint: l10n.t('When enabled the annotation can be scrolled into view when it is outside the viewport.'),
				enabledWhen: 'currentLine.enabled',
			},
			{
				kind: 'info',
				text: l10n.t(
					'Setting this to {disabledValue} will inhibit the hovers from showing over the annotation; Set {setting} to {location} to enable the hovers to show anywhere over the line.',
					{
						disabledValue: 'false',
						setting: 'gitlens.hovers.currentLine.over',
						location: 'line',
					},
				),
			},
		],
	},
	{
		id: 'code-lens',
		settingsSearch: 'gitlens.codeLens',
		name: l10n.t('Git CodeLens'),
		group: 'Editor',
		icon: 'gl-commit-horizontal',
		hint: l10n.t('Adds authorship CodeLens to the top of files and on code blocks'),
		master: {
			kind: 'check',
			key: 'codeLens.enabled',
			label: l10n.t('Git CodeLens'),
		},
		command: { label: l10n.t('GitLens: Toggle Git CodeLens'), command: 'gitlens.toggleCodeLens' },
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/gitlens-features/#git-codelens',
		preview: 'codelens',
		controls: [
			{
				kind: 'check',
				key: 'codeLens.recentChange.enabled',
				label: l10n.t('Add the author and date of the most recent change for the file or code block'),
				enabledWhen: 'codeLens.enabled',
			},
			{
				kind: 'check',
				key: 'codeLens.recentChange.command',
				label: l10n.t('When clicked'),
				valueOn: 'gitlens.showQuickCommitFileDetails',
				enabledWhen: 'codeLens.enabled & codeLens.recentChange.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'codeLens.recentChange.command',
				label: l10n.t('When clicked'),
				options: [
					{ value: 'gitlens.toggleFileBlame', label: l10n.t('toggles the file blame') },
					{ value: 'gitlens.toggleFileHeatmap', label: l10n.t('toggles the file heatmap') },
					{
						value: 'gitlens.toggleFileChanges',
						label: l10n.t('toggles the file changes since before the commit'),
					},
					{
						value: 'gitlens.toggleFileChangesOnly',
						label: l10n.t('toggles the file changes from the commit'),
					},
					{ value: 'gitlens.diffWithPrevious', label: l10n.t('opens changes with the previous revision') },
					{ value: 'gitlens.revealCommitInView', label: l10n.t('reveals the commit in the Side Bar') },
					{ value: 'gitlens.showCommitsInView', label: l10n.t('shows details of the commit') },
					{ value: 'gitlens.showQuickCommitDetails', label: l10n.t('shows quick details of the commit') },
					{
						value: 'gitlens.showQuickCommitFileDetails',
						label: l10n.t('shows quick file details of the commit (default)'),
					},
					{ value: 'gitlens.showQuickFileHistory', label: l10n.t('shows the current file history') },
					{ value: 'gitlens.showQuickRepoHistory', label: l10n.t('shows the current branch history') },
					{
						value: 'gitlens.openCommitOnRemote',
						label: l10n.t('opens the commit on the remote service (when available)'),
					},
					{
						value: 'gitlens.copyRemoteCommitUrl',
						label: l10n.t('copies the remote commit URL to the clipboard (when available)'),
					},
					{
						value: 'gitlens.openFileOnRemote',
						label: l10n.t('opens the file revision on the remote service (when available)'),
					},
					{
						value: 'gitlens.copyRemoteFileUrl',
						label: l10n.t('copies the remote file revision URL to the clipboard (when available)'),
					},
				],
				enabledWhen: 'codeLens.enabled & codeLens.recentChange.enabled & codeLens.recentChange.command !false',
				indent: true,
			},
			{
				kind: 'check',
				key: 'codeLens.authors.enabled',
				label: l10n.t('Add the number of authors and the most prominent author of the file or code block'),
				enabledWhen: 'codeLens.enabled',
			},
			{
				kind: 'check',
				key: 'codeLens.authors.command',
				label: l10n.t('When clicked'),
				valueOn: 'gitlens.toggleFileBlame',
				enabledWhen: 'codeLens.enabled & codeLens.authors.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'codeLens.authors.command',
				label: l10n.t('When clicked'),
				options: [
					{ value: 'gitlens.toggleFileBlame', label: l10n.t('toggles the file blame (default)') },
					{ value: 'gitlens.toggleFileHeatmap', label: l10n.t('toggles the file heatmap') },
					{
						value: 'gitlens.toggleFileChanges',
						label: l10n.t('toggles the file changes since before the commit'),
					},
					{
						value: 'gitlens.toggleFileChangesOnly',
						label: l10n.t('toggles the file changes from the commit'),
					},
					{ value: 'gitlens.diffWithPrevious', label: l10n.t('opens changes with the previous revision') },
					{ value: 'gitlens.revealCommitInView', label: l10n.t('reveals the commit in the Side Bar') },
					{ value: 'gitlens.showCommitsInView', label: l10n.t('searches for commits within the range') },
					{ value: 'gitlens.showQuickCommitDetails', label: l10n.t('shows quick details of the commit') },
					{
						value: 'gitlens.showQuickCommitFileDetails',
						label: l10n.t('show quick file details of the commit'),
					},
					{ value: 'gitlens.showQuickFileHistory', label: l10n.t('shows the current file history') },
					{ value: 'gitlens.showQuickRepoHistory', label: l10n.t('shows the current branch history') },
					{
						value: 'gitlens.openCommitOnRemote',
						label: l10n.t('opens the commit on the remote service (when available)'),
					},
					{
						value: 'gitlens.copyRemoteCommitUrl',
						label: l10n.t('copies the remote commit URL to the clipboard (when available)'),
					},
					{
						value: 'gitlens.copyRemoteFileUrl',
						label: l10n.t('copies the remote file revision URL to the clipboard (when available)'),
					},
					{
						value: 'gitlens.openFileOnRemote',
						label: l10n.t('opens the file revision on the remote service (when available)'),
					},
				],
				enabledWhen: 'codeLens.enabled & codeLens.authors.enabled & codeLens.authors.command !false',
				indent: true,
			},
			{
				kind: 'text',
				key: 'codeLens.dateFormat',
				label: l10n.t('Date format'),
				placeholder: l10n.t('defaults to `{setting}` value', { setting: 'defaultDateFormat' }),
				hint: l10n.t('Used for absolute dates in the Git CodeLens'),
				preview: { type: 'date', default: 'MMMM Do, YYYY h:mma', defaultLookup: 'defaultDateFormat' },
				enabledWhen: 'codeLens.enabled',
			},
			{
				kind: 'checkgroup',
				key: 'codeLens.scopes',
				label: l10n.t('Add CodeLens to the following scopes'),
				options: [
					{ value: 'document', label: l10n.t('File scope'), hint: l10n.t('At the top of the file') },
					{
						value: 'containers',
						label: l10n.t('Containers scope'),
						hint: l10n.t('At the start of modules, classes, interfaces, etc'),
					},
					{
						value: 'blocks',
						label: l10n.t('Block scope'),
						hint: l10n.t('At the start of functions, methods, etc'),
					},
				],
				enabledWhen: 'codeLens.enabled',
			},
		],
	},
	{
		id: 'status-bar',
		settingsSearch: 'gitlens.statusBar',
		name: l10n.t('Status Bar Blame'),
		group: 'Editor',
		icon: 'git-commit',
		hint: l10n.t('Adds a Git blame annotation about the current line to the status bar'),
		master: {
			kind: 'check',
			key: 'statusBar.enabled',
			label: l10n.t('Status Bar Blame'),
		},
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/gitlens-features/#status-bar-blame',
		preview: 'statusbar',
		controls: [
			{
				kind: 'check',
				key: 'statusBar.pullRequests.enabled',
				label: l10n.t('Show the Pull Request (if any) that introduced the commit'),
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'info',
				text: l10n.t('Requires a connection to a supported remote service (e.g. GitHub)'),
				visibleWhen: 'statusBar.pullRequests.enabled',
			},
			{
				kind: 'text',
				key: 'statusBar.format',
				label: l10n.t('Annotation format'),
				placeholder: "${author}, ${agoOrDate}${' via 'pullRequest}",
				defaultValue: "${author}, ${agoOrDate}${' via 'pullRequest}",
				preview: { type: 'commit', default: "${author}, ${agoOrDate}${' via 'pullRequest}" },
				tokens: true,
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'text',
				key: 'statusBar.dateFormat',
				label: l10n.t('Date format'),
				placeholder: l10n.t('defaults to `{setting}` value', { setting: 'defaultDateFormat' }),
				hint: l10n.t('Used for absolute dates in the annotation format above'),
				preview: { type: 'date', default: 'MMMM Do, YYYY h:mma', defaultLookup: 'defaultDateFormat' },
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'segmented',
				key: 'statusBar.alignment',
				label: l10n.t('Position the annotation on the'),
				options: [
					{ value: 'left', label: l10n.t('left') },
					{ value: 'right', label: l10n.t('right') },
				],
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'select',
				key: 'statusBar.command',
				label: l10n.t('When clicked'),
				options: [
					{ value: 'gitlens.toggleFileBlame', label: l10n.t('toggles the file blame') },
					{ value: 'gitlens.toggleFileHeatmap', label: l10n.t('toggles the file heatmap') },
					{
						value: 'gitlens.toggleFileChanges',
						label: l10n.t('toggles the file changes since before the commit'),
					},
					{
						value: 'gitlens.toggleFileChangesOnly',
						label: l10n.t('toggles the file changes from the commit'),
					},
					{ value: 'gitlens.toggleCodeLens', label: l10n.t('toggles the Git CodeLens') },
					{
						value: 'gitlens.diffWithPrevious',
						label: l10n.t('opens line changes with the previous revision'),
					},
					{ value: 'gitlens.diffWithWorking', label: l10n.t('opens line changes with the working file') },
					{ value: 'gitlens.revealCommitInView', label: l10n.t('reveals the commit in the Side Bar') },
					{ value: 'gitlens.showCommitsInView', label: l10n.t('shows details of the commit') },
					{
						value: 'gitlens.showQuickCommitDetails',
						label: l10n.t('shows quick details of the commit (default)'),
					},
					{
						value: 'gitlens.showQuickCommitFileDetails',
						label: l10n.t('shows quick file details of the commit'),
					},
					{ value: 'gitlens.showQuickFileHistory', label: l10n.t('shows the current file history') },
					{ value: 'gitlens.showQuickRepoHistory', label: l10n.t('shows the current branch history') },
					{
						value: 'gitlens.openCommitOnRemote',
						label: l10n.t('opens the commit on the remote service (when available)'),
					},
					{
						value: 'gitlens.copyRemoteCommitUrl',
						label: l10n.t('copies the remote commit URL to the clipboard (when available)'),
					},
					{
						value: 'gitlens.openFileOnRemote',
						label: l10n.t('opens the file revision on the remote service (when available)'),
					},
					{
						value: 'gitlens.copyRemoteFileUrl',
						label: l10n.t('copies the remote file revision URL to the clipboard (when available)'),
					},
				],
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'check',
				key: 'statusBar.reduceFlicker',
				label: l10n.t('Reduce flashing when updating the annotation'),
				hint: l10n.t(
					'Avoids clearing the previous blame information when changing lines to reduce status bar "flashing"',
				),
				enabledWhen: 'statusBar.enabled',
			},
			{
				kind: 'text',
				key: 'statusBar.tooltipFormat',
				label: l10n.t('Hover tooltip format'),
				placeholder: l10n.t('format (in markdown) of the hover shown over the status bar blame information'),
				defaultValue:
					"${avatar} &nbsp;__${author}__ &nbsp;$(history) ${agoAndDateBothSources}${' via  'pullRequest} ${message}${\n\n---\n\nfootnotes}\n\n${commands}",
				preview: { type: 'commit', default: '${avatar} &nbsp;__${author}__ &nbsp;$(history) ${agoOrDate}' },
				tokens: 'hover',
				enabledWhen: 'statusBar.enabled',
			},
		],
	},
	{
		id: 'hovers',
		settingsSearch: 'gitlens.hovers',
		name: l10n.t('Hovers'),
		group: 'Editor',
		icon: 'comment',
		hint: l10n.t('Adds detailed blame information accessible via hovers'),
		master: {
			kind: 'check',
			key: 'hovers.enabled',
			label: l10n.t('Hovers'),
		},
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/gitlens-features/#hovers',
		preview: 'hover',
		controls: [
			{
				kind: 'check',
				key: 'hovers.avatars',
				label: l10n.t('Use author avatars'),
				enabledWhen: 'hovers.enabled',
			},
			{
				kind: 'check',
				key: 'hovers.autolinks.enabled',
				label: l10n.t('Show autolinks in commit messages'),
				enabledWhen: 'hovers.enabled',
			},
			{
				kind: 'check',
				key: 'hovers.autolinks.enhanced',
				label: l10n.t('Enhance autolinks with remote details'),
				hint: l10n.t('Requires a connection to a supported remote service (e.g. GitHub)'),
				enabledWhen: 'hovers.enabled & hovers.autolinks.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.pullRequests.enabled',
				label: l10n.t('Show the Pull Request (if any) that introduced the commit'),
				enabledWhen: 'hovers.enabled',
			},
			{
				kind: 'info',
				text: l10n.t('Requires a connection to a supported remote service (e.g. GitHub)'),
				visibleWhen: 'hovers.pullRequests.enabled',
			},
			{
				kind: 'check',
				key: 'hovers.currentLine.enabled',
				label: l10n.t('Show hovers for the current line'),
				enabledWhen: 'hovers.enabled',
				visibleWhen: 'currentLine.enabled',
			},
			{
				kind: 'check',
				key: 'hovers.currentLine.enabled',
				label: l10n.t('Show hovers for the current line'),
				addSettingsOn: [['hovers.currentLine.over', 'line']],
				enabledWhen: 'hovers.enabled',
				visibleWhen: 'currentLine.enabled =false',
			},
			{
				kind: 'select',
				key: 'hovers.currentLine.over',
				label: l10n.t('Shown when over the'),
				options: [
					{ value: 'annotation', label: l10n.t('annotation only') },
					{ value: 'line', label: l10n.t('line & annotation') },
				],
				enabledWhen: 'hovers.enabled & hovers.currentLine.enabled',
				visibleWhen: 'currentLine.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'hovers.currentLine.over',
				label: l10n.t('Shown when over the'),
				options: [
					{ value: 'annotation', label: l10n.t('annotation only') },
					{ value: 'line', label: l10n.t('line') },
				],
				enabledWhen: 'hovers.enabled & hovers.currentLine.enabled & currentLine.enabled',
				visibleWhen: 'currentLine.enabled =false',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.currentLine.details',
				label: l10n.t('Add blame details'),
				enabledWhen: 'hovers.enabled & hovers.currentLine.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.currentLine.changes',
				label: l10n.t('Add changes (diff)'),
				enabledWhen: 'hovers.enabled & hovers.currentLine.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.annotations.enabled',
				label: l10n.t('Show hovers while annotating'),
				enabledWhen: 'hovers.enabled',
			},
			{
				kind: 'select',
				key: 'hovers.annotations.over',
				label: l10n.t('Shown when over the'),
				options: [
					{ value: 'annotation', label: l10n.t('annotation only') },
					{ value: 'line', label: l10n.t('line & annotation') },
				],
				enabledWhen: 'hovers.enabled & hovers.annotations.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.annotations.details',
				label: l10n.t('Add blame details'),
				enabledWhen: 'hovers.enabled & hovers.annotations.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'hovers.annotations.changes',
				label: l10n.t('Add changes (diff)'),
				enabledWhen: 'hovers.enabled & hovers.annotations.enabled',
				indent: true,
			},
			{
				kind: 'text',
				key: 'hovers.detailsMarkdownFormat',
				label: l10n.t('Commit details format'),
				placeholder: l10n.t('format (in markdown) of the commit details hover'),
				defaultValue:
					"${avatar} &nbsp;__${author}__${signature} &nbsp;$(history) ${agoAndDateBothSources}${' via  'pullRequest} ${message}${\n\n---\n\nfootnotes}\n\n${commands}",
				preview: { type: 'commit', default: '${avatar} &nbsp;__${author}__ &nbsp;$(history) ${agoOrDate}' },
				tokens: 'hover',
				enabledWhen: 'hovers.enabled',
			},
		],
	},
];
