import * as l10n from '@vscode/l10n';
import type { SettingsCategory } from '../model.js';

export const generalCategories: SettingsCategory[] = [
	{
		id: 'dates',
		settingsSearch: 'gitlens.default',
		name: l10n.t('Dates & Times'),
		group: 'General',
		icon: 'calendar',
		hint: l10n.t('Controls how dates and times are formatted and displayed throughout GitLens'),
		controls: [
			{
				kind: 'check',
				key: 'defaultDateStyle',
				label: l10n.t('Allow relative date formatting'),
				valueOn: 'relative',
				valueOff: 'absolute',
			},
			{
				kind: 'info',
				text: l10n.t('Shows some dates relatively, e.g. 1 day ago'),
				visibleWhen: 'defaultDateStyle =relative',
			},
			{
				kind: 'info',
				text: l10n.t('Shows dates absolutely, using the date format below'),
				visibleWhen: 'defaultDateStyle =absolute',
			},
			{
				kind: 'text',
				key: 'defaultDateLocale',
				label: l10n.t('Date locale'),
				placeholder: l10n.t('defaults to VS Code locale'),
				hint: l10n.t(
					'Use "{system}" for the system locale, or a [locale language tag]({url}), e.g. {example}',
					{
						system: 'system',
						url: 'https://en.wikipedia.org/wiki/IETF_language_tag',
						example: 'en-US',
					},
				),
				preview: { type: 'date-locale', defaultLookup: 'defaultDateFormat' },
			},
			{
				kind: 'text',
				key: 'defaultDateFormat',
				label: l10n.t('Date format'),
				placeholder: l10n.t('defaults to {format}', { format: 'MMMM Do, YYYY h:mma' }),
				hint: l10n.t('See the [Moment.js docs]({url}) for supported formats', {
					url: 'https://momentjs.com/docs/#/displaying/format/',
				}),
				preview: { type: 'date', default: 'MMMM Do, YYYY h:mma' },
			},
			{
				kind: 'text',
				key: 'defaultDateShortFormat',
				label: l10n.t('Short date format'),
				placeholder: l10n.t('defaults to system short date format'),
				preview: { type: 'date', default: 'short' },
			},
			{
				kind: 'text',
				key: 'defaultTimeFormat',
				label: l10n.t('Time format'),
				placeholder: l10n.t('defaults to {format}', { format: 'h:mma' }),
				preview: { type: 'date', default: 'h:mma' },
			},
			{
				kind: 'select',
				key: 'defaultDateSource',
				label: l10n.t('Use the'),
				options: [
					{ value: 'authored', label: l10n.t('authored date (default)') },
					{ value: 'committed', label: l10n.t('committed date') },
				],
				hint: l10n.t('Specifies whether commit dates should use the authored or committed date'),
			},
		],
	},
	{
		id: 'menus',
		settingsSearch: 'gitlens.menus',
		name: l10n.t('Menus & Toolbars'),
		group: 'General',
		icon: 'ellipsis',
		hint: l10n.t('Adds many helpful commands to the built-in menus & toolbars'),
		master: {
			kind: 'check',
			key: 'menus',
			label: l10n.t('Menus & Toolbars'),
			checkedRemoves: true,
		},
		controls: [
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor',
				label: l10n.t('Add to the editor context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor.compare',
				label: l10n.t('Add an Open Changes submenu'),
				enabledWhen: 'menus.editor',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor.remote',
				label: l10n.t('Add an Open on Remote (Web) submenu'),
				enabledWhen: 'menus.editor',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor.blame',
				label: l10n.t('Add a File Annotations submenu'),
				enabledWhen: 'menus.editor',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor.history',
				label: l10n.t('Add a File History submenu'),
				enabledWhen: 'menus.editor',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editor.clipboard',
				label: l10n.t('Add to the Copy As submenu'),
				enabledWhen: 'menus.editor',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGutter',
				label: l10n.t("Add to the editor's line number (gutter) context menu"),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGutter.blame',
				label: 'Add a File Annotations submenu',
				enabledWhen: 'menus.editorGutter',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGutter.share',
				label: l10n.t('Add a Share submenu'),
				enabledWhen: 'menus.editorGutter',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGutter.compare',
				label: l10n.t('Add an Open Changes submenu'),
				enabledWhen: 'menus.editorGutter',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGutter.remote',
				label: l10n.t('Add an Open on Remote (Web) submenu'),
				enabledWhen: 'menus.editorGutter',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorTab',
				label: l10n.t('Add to the editor tab context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorTab.clipboard',
				label: l10n.t('Add Copy Remote File URL * commands'),
				enabledWhen: 'menus.editorTab',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorTab.compare',
				label: l10n.t('Add an Open Changes submenu'),
				enabledWhen: 'menus.editorTab',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorTab.remote',
				label: l10n.t('Add an Open on Remote (Web) submenu'),
				enabledWhen: 'menus.editorTab',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorTab.history',
				label: l10n.t('Add a File History submenu'),
				enabledWhen: 'menus.editorTab',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGroup',
				label: l10n.t('Add to the editor group toolbar'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGroup.compare',
				label: l10n.t('Add revision history navigation commands'),
				enabledWhen: 'menus.editorGroup',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'editorGroup.blame',
				// Legacy was a composite row: checkbox labeled 'Add' followed by the select below
				label: l10n.t('Add a File Annotations submenu or command'),
				enabledWhen: 'menus.editorGroup',
				indent: true,
			},
			{
				kind: 'select',
				key: 'fileAnnotations.command',
				label: l10n.t('Add'),
				options: [
					{ value: 'null', label: l10n.t('File Annotations submenu') },
					{ value: 'blame', label: l10n.t('Toggle File Blame command') },
					{ value: 'heatmap', label: l10n.t('Toggle File Heatmap command') },
					{ value: 'changes', label: l10n.t('Toggle File Changes command') },
				],
				enabledWhen: 'menus.editorGroup & menus.editorGroup.blame',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'explorer',
				label: l10n.t('Add to the Explorer items context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'explorer.compare',
				label: l10n.t('Add an Open Changes submenu'),
				enabledWhen: 'menus.explorer',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'explorer.remote',
				label: l10n.t('Add an Open on Remote (Web) submenu'),
				enabledWhen: 'menus.explorer',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'explorer.history',
				label: l10n.t('Add a File History submenu'),
				enabledWhen: 'menus.explorer',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'explorer.clipboard',
				label: l10n.t('Add Copy Remote File URL * commands'),
				enabledWhen: 'menus.explorer',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'ghpr',
				label: l10n.t("Add to the GitHub Pull Request and Issues' pull request context menu"),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'ghpr.worktree',
				label: l10n.t('Add an Open Worktree for Pull Request command'),
				// The legacy partial had data-enablement="menus.scm" here — a copy/paste error
				// (flagged in parity-verification); the correct parent is menus.ghpr
				enabledWhen: 'menus.ghpr',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scm',
				label: l10n.t('Add to the Source Control context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scm.graph',
				label: l10n.t('Add a Show Commit Graph command'),
				enabledWhen: 'menus.scm',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scm.visualHistory',
				label: l10n.t('Add a Visualize Repository History command'),
				enabledWhen: 'menus.scm',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepositoryInline',
				label: l10n.t('Add to the Source Control repository toolbar'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepositoryInline.stash',
				label: l10n.t('Add a Stash All Changes command'),
				enabledWhen: 'menus.scmRepositoryInline',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepositoryInline.graph',
				label: l10n.t('Add a Show Commit Graph command'),
				enabledWhen: 'menus.scmRepositoryInline',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepositoryInline.visualHistory',
				label: l10n.t('Add a Visualize Repository History command'),
				enabledWhen: 'menus.scmRepositoryInline',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepository',
				label: l10n.t('Add to the Source Control repository context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepository.generateCommitMessage',
				label: l10n.t('Add a Generate Commit Message (Experimental) command'),
				enabledWhen: 'menus.scmRepository',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepository.authors',
				label: l10n.t('Add an Add Co-authors command'),
				enabledWhen: 'menus.scmRepository',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepository.graph',
				label: l10n.t('Add a Show Commit Graph command'),
				enabledWhen: 'menus.scmRepository',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmRepository.visualHistory',
				label: l10n.t('Add a Visualize Repository History command'),
				enabledWhen: 'menus.scmRepository',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroupInline',
				label: l10n.t('Add to the Source Control groups toolbar'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroupInline.stash',
				label: l10n.t('Add a Stash All Changes command'),
				enabledWhen: 'menus.scmGroupInline',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroup',
				label: l10n.t('Add to the Source Control groups context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroup.stash',
				label: l10n.t('Add a Stash All Changes command'),
				enabledWhen: 'menus.scmGroup',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroup.compare',
				label: l10n.t('Add an Open Changes submenu'),
				enabledWhen: 'menus.scmGroup',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroup.openClose',
				label: l10n.t('Add Open Changed Files and Close Unchanged Files commands'),
				enabledWhen: 'menus.scmGroup',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmGroup.patch',
				label: l10n.t('Add Copy as Patch and Share as Cloud Patch... commands'),
				enabledWhen: 'menus.scmGroup',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItemInline',
				label: l10n.t('Add to the Source Control items toolbar'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItemInline.stash',
				label: l10n.t('Add a Stash Changes command'),
				enabledWhen: 'menus.scmItemInline',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem',
				label: l10n.t('Add to the Source Control items context menu'),
				checkedRemoves: true,
				enabledWhen: 'menus',
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.compare',
				label: l10n.t('Add an Open Changes with submenu'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.remote',
				label: l10n.t('Add an Open on Remote (Web) submenu'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.history',
				label: l10n.t('Add a File History submenu'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.stash',
				label: l10n.t('Add a Stash Changes command'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.share',
				label: l10n.t('Add a Share submenu'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
			{
				kind: 'check',
				type: 'object',
				key: 'menus',
				path: 'scmItem.clipboard',
				label: l10n.t('Add a Copy Relative Path command'),
				enabledWhen: 'menus.scmItem',
				indent: true,
			},
		],
	},
];
