import type { SettingsCategory } from '../model.js';

export const views2Categories: SettingsCategory[] = [
	{
		id: 'commit-details-view',
		settingsSearch: 'gitlens.views.commitDetails or gitlens.views',
		name: 'Inspect view',
		group: 'Views',
		icon: 'gl-commit-view',
		hint: 'Adds an [Inspect view](command:gitlens.showCommitDetailsView) to see rich details for a commit',
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/gitlens-features/#commit-details-view',
		controls: [
			{
				kind: 'check',
				key: 'views.commitDetails.autolinks.enabled',
				label: 'Show autolinks in commit messages',
			},
			{
				kind: 'check',
				key: 'views.commitDetails.autolinks.enhanced',
				label: 'Enhance autolinks with remote details',
				hint: 'Requires a connection to a supported remote service (e.g. GitHub)',
				enabledWhen: 'views.commitDetails.autolinks.enabled',
				indent: true,
			},
			{
				kind: 'check',
				key: 'views.commitDetails.pullRequests.enabled',
				label: 'Show the Pull Request (if any) that introduced the commit',
				hint: 'Requires a connection to a supported remote service (e.g. GitHub)',
			},
			{
				kind: 'select',
				key: 'views.commitDetails.files.layout',
				label: 'Layout files',
				hint: 'Chooses the best layout based on the number of files at each nesting level',
				options: [
					{ value: 'auto', label: 'automatically' },
					{ value: 'list', label: 'as a list' },
					{ value: 'tree', label: 'as a tree' },
				],
			},
			{
				kind: 'check',
				key: 'views.commitDetails.files.compact',
				label: 'Use compact file layout',
				hint: 'Compacts (flattens) unnecessary nesting when using a tree layouts',
			},
			{
				kind: 'check',
				key: 'views.commitDetails.avatars',
				label: 'Use author avatars',
			},
		],
	},
	{
		id: 'contributors-view',
		settingsSearch: 'gitlens.views.contributors or gitlens.views',
		name: 'Contributors view',
		group: 'Views',
		icon: 'gl-contributors-view',
		hint: 'Adds a [Contributors view](command:gitlens.showContributorsView), hidden by default, to visualize, navigate, and explore contributors',
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/side-bar/#contributors-view',
		controls: [
			{
				kind: 'check',
				key: 'views.contributors.showAllBranches',
				label: 'Show commits from all branches',
			},
			{
				kind: 'check',
				key: 'views.contributors.pullRequests.enabled',
				label: 'Show associated pull requests',
				hint: 'Requires a connection to a supported remote service (e.g. GitHub)',
			},
			{
				kind: 'check',
				key: 'views.contributors.pullRequests.showForCommits',
				label: 'Show the pull request that introduced each commit',
				enabledWhen: 'views.contributors.pullRequests.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'views.contributors.files.layout',
				label: 'Layout files',
				hint: 'Chooses the best layout based on the number of files at each nesting level',
				options: [
					{ value: 'auto', label: 'automatically' },
					{ value: 'list', label: 'as a list' },
					{ value: 'tree', label: 'as a tree' },
				],
			},
			{
				kind: 'select',
				key: 'views.contributors.files.icon',
				label: 'File icons',
				options: [
					{ value: 'type', label: 'show file type (default)' },
					{ value: 'status', label: 'show file status' },
				],
			},
			{
				kind: 'check',
				key: 'views.contributors.files.compact',
				label: 'Use compact file layout',
				hint: 'Compacts (flattens) unnecessary nesting when using a tree layouts',
			},
			{
				kind: 'check',
				key: 'views.contributors.avatars',
				label: 'Use author avatars',
			},
		],
	},
	{
		id: 'file-history-view',
		settingsSearch: 'gitlens.views.fileHistory or gitlens.views',
		name: 'File History view',
		group: 'Views',
		icon: 'gl-history-view',
		hint: 'Adds a [File History view](command:gitlens.showFileHistoryView) to visualize, navigate, and explore the revision history of the current file, a specified file or folder, or just the selected lines of the current file',
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/side-bar/#file-history-view',
		controls: [
			{
				kind: 'check',
				key: 'views.fileHistory.avatars',
				label: 'Use author avatars',
			},
			{
				kind: 'info',
				text: 'Applies only when showing folder history:',
			},
			{
				kind: 'check',
				key: 'views.fileHistory.pullRequests.enabled',
				label: 'Show associated pull requests',
				hint: 'Requires a connection to a supported remote service (e.g. GitHub)',
				indent: true,
			},
			{
				kind: 'check',
				key: 'views.fileHistory.pullRequests.showForCommits',
				label: 'Show the pull request that introduced each commit',
				enabledWhen: 'views.fileHistory.pullRequests.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'views.fileHistory.files.layout',
				label: 'Layout files',
				hint: 'Chooses the best layout based on the number of files at each nesting level',
				options: [
					{ value: 'auto', label: 'automatically' },
					{ value: 'list', label: 'as a list' },
					{ value: 'tree', label: 'as a tree' },
				],
				indent: true,
			},
			{
				kind: 'select',
				key: 'views.fileHistory.files.icon',
				label: 'File icons',
				options: [
					{ value: 'type', label: 'show file type (default)' },
					{ value: 'status', label: 'show file status' },
				],
				indent: true,
			},
			{
				kind: 'check',
				key: 'views.fileHistory.files.compact',
				label: 'Use compact file layout',
				hint: 'Compacts (flattens) unnecessary nesting when using a tree layouts',
				indent: true,
			},
		],
	},
	{
		id: 'line-history-view',
		settingsSearch: 'gitlens.views.lineHistory or gitlens.views',
		name: 'Line History view',
		group: 'Views',
		icon: 'gl-history-view',
		hint: 'Adds a [Line History view](command:gitlens.showLineHistoryView), hidden by default, to visualize, navigate, and explore the revision history of the selected lines of current file',
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/side-bar/#line-history-view',
		controls: [
			{
				kind: 'check',
				key: 'views.lineHistory.avatars',
				label: 'Use author avatars',
			},
		],
	},
	{
		id: 'search-compare-view',
		settingsSearch: 'gitlens.views.searchAndCompare or gitlens.views',
		name: 'Search & Compare view',
		group: 'Views',
		icon: 'gl-search-view',
		hint: 'Adds a [Search & Compare view](command:gitlens.showSearchAndCompareView) to search and explore commit histories by message, author, files, id, etc, or visualize comparisons between branches, tags, commits, and more',
		learnMoreUrl: 'https://help.gitkraken.com/gitlens/side-bar/#search-compare-view',
		controls: [
			{
				kind: 'check',
				key: 'views.searchAndCompare.pullRequests.enabled',
				label: 'Show associated pull requests',
				hint: 'Requires a connection to a supported remote service (e.g. GitHub)',
			},
			{
				kind: 'check',
				key: 'views.searchAndCompare.pullRequests.showForCommits',
				label: 'Show the pull request that introduced each commit',
				enabledWhen: 'views.searchAndCompare.pullRequests.enabled',
				indent: true,
			},
			{
				kind: 'select',
				key: 'views.searchAndCompare.files.layout',
				label: 'Layout files',
				options: [
					{ value: 'auto', label: 'automatically' },
					{ value: 'list', label: 'as a list' },
					{ value: 'tree', label: 'as a tree' },
				],
			},
			{
				kind: 'select',
				key: 'views.searchAndCompare.files.icon',
				label: 'File icons',
				options: [
					{ value: 'type', label: 'show file type (default)' },
					{ value: 'status', label: 'show file status' },
				],
			},
			{
				kind: 'check',
				key: 'views.searchAndCompare.files.compact',
				label: 'Use compact file layout',
				hint: 'Compacts (flattens) unnecessary nesting when using a tree layouts',
			},
			{
				kind: 'check',
				key: 'views.searchAndCompare.avatars',
				label: 'Use author avatars',
			},
		],
	},
];
