export {
	type AgentProviderCallbacks,
	type AgentSessionHistoryActions,
	type AgentSessionHistoryDisposition,
	type AgentSessionHistoryItem,
	type AgentSessionHistoryOptions,
	type AgentSessionHistoryResult,
	type AgentSession,
	type AgentSessionPhase,
	type AgentSessionProvider,
	type AgentSessionResumeOutcome,
	type AgentSessionResumeTarget,
	type AgentSessionStatus,
	getPhaseForStatus,
	isActiveAgentPhase,
	type PendingPermission,
	type PendingPermissionKind,
	type PermissionDecision,
	type PermissionSuggestion,
} from '@gitlens/agents/types.js';
