/**
 * GitLens Localization E2E
 *
 * Launches the editor once per locale in {@link locales} and asserts that a small, fixed set of
 * well-known labels render that locale's catalog entry. Two intents share this file because they
 * share every mechanism except which catalog is read:
 *
 * - `qps-ploc` (Microsoft's pseudo-locale, catalog generated by `generate:l10n:pseudo`) is a
 *   regression net for the next string that ships unwrapped in an `l10n.t(...)` call.
 * - Each shipped locale (`es`, `zh-cn`, `zh-tw`) proves that VS Code resolves GitLens' catalogs for
 *   a REAL display language, not only for the pseudo one — the catalogs users actually receive
 *   (measured: `.vscodeignore` excludes only the `qps-ploc` pair, so every other catalog ships).
 *
 * Neither is a coverage audit: `check:l10n` validates all ~6800 runtime and ~2300 manifest entries
 * statically on every PR, and does it far better than any UI assertion could. What only an E2E run
 * can show is that the catalog is selected and delivered end to end.
 *
 * Expected text is always read from the catalog file rather than re-implemented here, so the test
 * cannot drift from what the repository actually ships (or from what `generate:l10n:pseudo`
 * produces). `beforeAll` rejects any candidate key that is missing from a locale's catalog or
 * identical to its English source — a key a translator legitimately left as-is (`Stashes` in `es`)
 * would otherwise make its assertion pass while proving nothing.
 *
 * Both catalog kinds are exercised, because they travel different paths:
 *
 * - RUNTIME (`l10n.t(...)`, `l10n/bundle.l10n.<locale>.json`) — selected by `vscode.env.language`.
 *   The Graph's sidebar panel headers and the Git Commands placeholders cover it. Note these are
 *   ONE delivery fact observed at two surfaces, not two independent ones: the webview receives the
 *   host's already-selected bundle through a `<meta>` tag rather than resolving a catalog itself.
 * - MANIFEST (`package.nls.<locale>.json`) — substituted by VS Code itself at extension-scan time.
 *   Only a command palette entry can test it: a webview's title never reaches the DOM here (the
 *   `title` attribute of GitLens' frames measured empty), and the sidebar pane headers look like
 *   manifest strings but are not — GitLens re-titles its webview views at runtime, so `es` renders
 *   `Grafo de commits` (runtime `l10n.t('Commit Graph')`) where the manifest says `Grafo`.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import * as process from 'node:process';
import type { FrameLocator, Locator } from '@playwright/test';
import { test as base, createTmpDir, expect, GitFixture, MaxTimeout } from '../baseTest.js';
import { widenSideBarForGraph } from '../graphHelpers.js';

/** Repo root — this file lives at `tests/e2e/specs/`, three levels below it. */
const repoRoot = path.resolve(__dirname, '../../..');

/** Locales to exercise: the pseudo-locale, and every locale GitLens ships a catalog for. */
const locales = ['qps-ploc', 'es', 'zh-cn', 'zh-tw'] as const;

/**
 * Candidate keys, each verified in `beforeAll` to exist in every catalog and differ from English.
 * `chooseSubcommandKey` is rendered with its `{0}` placeholder substituted.
 */
const branchesKey = 'Branches';
const worktreesKey = 'Worktrees';
const chooseCommandKey = 'Choose a command';
const chooseSubcommandKey = 'Choose a {0} command';
/** Manifest key — the `contributes.commands` title for `gitlens.showGraph`. */
const showGraphCommandKey = 'command.gitlens.showGraph.title';

type Catalog = Record<string, string | { message: string }>;

/** A catalog entry's text — the English source stores some entries as `{ message, comment }`. */
function message(catalog: Catalog, key: string): string | undefined {
	const value = catalog[key];

	return typeof value === 'object' ? value.message : value;
}

function loadCatalog(file: string): Catalog {
	return JSON.parse(readFileSync(file, 'utf8')) as Catalog;
}

/** Escapes a literal string for embedding inside a `RegExp` source. */
function escapeForRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Builds a `^...$` pattern from an `l10n.t('...{0}...')`-style template, matching the template's
 * literal text exactly and accepting any (non-empty) substitution for `{0}`. Used for the nested
 * Git wizard placeholder, whose substituted command name is itself localized — asserting on the
 * surrounding literal text is what actually verifies the template stayed localized.
 */
function patternFromTemplate(template: string): RegExp {
	const [prefix, suffix] = template.split('{0}');

	return new RegExp(`^${escapeForRegExp(prefix)}.+${escapeForRegExp(suffix)}$`);
}

for (const locale of locales) {
	const test = base.extend({
		vscodeOptions: [
			{
				vscodeVersion: process.env.VSCODE_VERSION ?? 'stable',
				locale: locale,
				setup: async () => {
					const repoDir = await createTmpDir();
					const git = new GitFixture(repoDir);
					await git.init();
					await git.commit('Initial commit', 'file.txt', 'content\n');

					return repoDir;
				},
			},
			{ scope: 'worker' },
		],
	});

	let englishRuntime: Catalog;
	let englishManifest: Catalog;
	let runtime: Catalog;
	let manifest: Catalog;

	test.beforeAll(() => {
		const runtimePath = path.join(repoRoot, 'l10n', `bundle.l10n.${locale}.json`);
		const manifestPath = path.join(repoRoot, `package.nls.${locale}.json`);

		// The pseudo catalogs are generated and git-ignored; every shipped locale's are committed.
		if (locale === 'qps-ploc' && !(existsSync(runtimePath) && existsSync(manifestPath))) {
			execFileSync('pnpm', ['run', 'generate:l10n:pseudo'], { cwd: repoRoot, stdio: 'inherit' });
		}

		englishRuntime = loadCatalog(path.join(repoRoot, 'l10n', 'bundle.l10n.json'));
		englishManifest = loadCatalog(path.join(repoRoot, 'package.nls.json'));
		runtime = loadCatalog(runtimePath);
		manifest = loadCatalog(manifestPath);

		for (const [key, source, catalog, file] of [
			[branchesKey, englishRuntime, runtime, path.basename(runtimePath)],
			[worktreesKey, englishRuntime, runtime, path.basename(runtimePath)],
			[chooseCommandKey, englishRuntime, runtime, path.basename(runtimePath)],
			[chooseSubcommandKey, englishRuntime, runtime, path.basename(runtimePath)],
			[showGraphCommandKey, englishManifest, manifest, path.basename(manifestPath)],
		] as const) {
			if (message(source, key) == null) {
				throw new Error(
					`Candidate localization key ${JSON.stringify(key)} is missing from its English source — ` +
						`pick a different well-known label for this test.`,
				);
			}

			const translated = message(catalog, key);
			if (translated == null) {
				throw new Error(
					`Candidate localization key ${JSON.stringify(key)} is missing from ${file} — that locale ` +
						`falls back to English for it, so it cannot carry an assertion. Pick a different key.`,
				);
			}

			// A key the translator legitimately left in English would let its assertion pass while
			// proving nothing, so it is rejected here rather than silently weakening the test.
			if (translated === message(source, key)) {
				throw new Error(
					`Candidate localization key ${JSON.stringify(key)} is identical to its English source in ` +
						`${file} — pick a different key for this locale.`,
				);
			}
		}
	});

	/**
	 * Asserts the Graph sidebar panel header settles on `key`'s entry for this locale.
	 *
	 * Gating on the text rather than on `toBeVisible()` is deliberate. The header title is a flex item with
	 * `min-width: 0` and an ellipsis, sharing its row with an actions toolbar that does not shrink, so a
	 * narrow side bar legitimately squeezes it to zero width — mounted, `checkVisibility()`-true, and
	 * reported `hidden` by Playwright only because its box is empty. That says nothing about whether the
	 * string was localized, which is all this test is about.
	 *
	 * `toHaveText` rather than a poll over `textContent()`, because the header is not merely narrow when
	 * something goes wrong — it is gone: the panel renders `nothing` while no panel is active, so the node
	 * is detached. `textContent()` on a detached locator waits out `actionTimeout` (30s, three times this
	 * assertion's own budget) and then throws, and `expect.poll` evaluates its callback outside the try it
	 * retries on, so that throw ends the assertion with a bare action timeout and never reaches the message
	 * below. A locator assertion retries against its own deadline instead, detached node and all.
	 */
	async function expectPanelHeaderLocalized(header: Locator, key: string, label: string): Promise<void> {
		await expect(header, `${label} never rendered the ${locale} catalog entry`).toHaveText(message(runtime, key)!, {
			timeout: MaxTimeout,
		});
	}

	test.describe(`Localization — ${locale}`, () => {
		test.describe.configure({ mode: 'serial' });

		test.beforeEach(async ({ vscode }) => {
			test.skip(!(await vscode.gitlens.hasActivityBar()), 'Editor has no standard activity bar (e.g. Cursor)');

			// Establish the precondition separately from the assertions it underpins: without this, a
			// language pack the editor declined shows up as a wall of "expected <translated>, got <English>"
			// text mismatches instead of naming the one thing that actually went wrong.
			expect(await vscode.gitlens.getLanguage(), 'Editor did not resolve the requested display language').toBe(
				locale,
			);
		});

		test('Graph sidebar panel headers render localized', async ({ vscode }) => {
			// The Graph is Pro-gated — without a simulated subscription the view renders its Welcome/
			// account-gate content instead, and never mounts the Graph app at all.
			await using _subscription = await vscode.gitlens.startSubscriptionSimulation({ state: 6, planId: 'pro' });

			await vscode.gitlens.showCommitGraphView();
			await widenSideBarForGraph(vscode);

			// Find the Graph's own content frame structurally — by a DOM element only the Graph app
			// renders (the sidebar rail's Branches icon) — rather than by the webview's title, which is a
			// manifest string that never reaches the DOM here. Structural lookup also doesn't care that
			// another GitLens webviewView (a Welcome view) may be mounted alongside the Graph.
			const outerFrames = vscode.page.locator(
				'iframe.webview[src*="extensionId=eamodio.gitlens"][src*="purpose=webviewView"]',
			);
			await expect.poll(() => outerFrames.count(), { timeout: MaxTimeout }).toBeGreaterThan(0);

			// The outer frame appears before the Graph app has mounted inside it, so poll for the rail icon
			// rather than checking each frame once.
			let graphContent: FrameLocator | undefined;
			await expect
				.poll(
					async () => {
						const count = await outerFrames.count();
						for (let i = 0; i < count; i++) {
							const content = outerFrames
								.nth(i)
								.contentFrame()
								.locator('iframe#active-frame')
								.contentFrame();
							if ((await content.locator('button[data-roving-key="icon:branches"]').count()) > 0) {
								graphContent = content;
								return true;
							}
						}

						return false;
					},
					{
						message: 'Could not find the Commit Graph webview among the open GitLens webviews',
						timeout: MaxTimeout,
					},
				)
				.toBe(true);

			const panelHeader = graphContent!.locator('.header-title__text').first();

			await graphContent!.locator('button[data-roving-key="icon:branches"]').click();
			await expectPanelHeaderLocalized(panelHeader, branchesKey, 'Graph Branches sidebar panel header');

			await graphContent!.locator('button[data-roving-key="icon:worktrees"]').click();
			await expectPanelHeaderLocalized(panelHeader, worktreesKey, 'Graph Worktrees sidebar panel header');
		});

		test('Git Commands quick pick renders localized placeholders', async ({ vscode }) => {
			await vscode.gitlens.executeCommand('gitlens.gitCommands');
			await vscode.gitlens.quickPick.waitForVisible();

			expect(await vscode.gitlens.quickPick.getPlaceholder(), 'Git Commands root placeholder').toBe(
				message(runtime, chooseCommandKey),
			);

			// Click the first item by position — deterministic regardless of the localized item labels,
			// which typed-text filtering could not fuzzy-match. Any command works: the assertion below is
			// on the template's literal text, not on which command was chosen.
			const rootPlaceholder = await vscode.gitlens.quickPick.getPlaceholder();
			await vscode.gitlens.quickPick.firstResult.click();
			await expect
				.poll(() => vscode.gitlens.quickPick.getPlaceholder(), { timeout: MaxTimeout })
				.not.toBe(rootPlaceholder);

			expect(
				await vscode.gitlens.quickPick.getPlaceholder(),
				'Git Commands subcommand placeholder did not match the localized template',
			).toMatch(patternFromTemplate(message(runtime, chooseSubcommandKey)!));

			await vscode.gitlens.quickPick.cancel();
		});

		test('Command palette renders the manifest-localized command title', async ({ vscode }) => {
			const englishTitle = message(englishManifest, showGraphCommandKey)!;
			const localizedTitle = message(manifest, showGraphCommandKey)!;

			await vscode.page.keyboard.press('Control+Shift+P');

			const rows = vscode.page.locator('.quick-input-widget .monaco-list-row');
			await expect(rows.first(), 'Command palette never opened').toBeVisible({ timeout: MaxTimeout });

			// Filter by the ENGLISH title on purpose. VS Code keeps the original as a searchable alias and
			// renders it as a "similar commands" line beneath the localized label, so this matches in every
			// locale — and a row that matched an English filter while displaying the localized title is
			// exactly the evidence wanted. Filtering by the localized title instead would make the test
			// depend on the locale's own input handling rather than on the substitution under test.
			await vscode.page.keyboard.type(englishTitle);

			await expect
				.poll(async () => (await rows.allTextContents()).some(text => text.includes(localizedTitle)), {
					message: `No command palette row rendered the ${locale} manifest title ${JSON.stringify(localizedTitle)}`,
					timeout: MaxTimeout,
				})
				.toBe(true);

			await vscode.page.keyboard.press('Escape');
		});
	});
}
